# Site settings
title:          "Wahyu Kristianto"
description:    "Creator, Author, Husband, Dad • Making ♥ with thinking & typing •"
baseurl:        ""
url:            "https://wahyukristianto.com"

# Google Analytics
google_analytics: UA-156793259-1

# Author
author:
  name:         Wahyu Kristianto
  url:          https://wahyukristianto.com
  email:        w.kristories@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /blog/post/:title
paginate:       5
paginate_path: /blog/page/:num/

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
#disqus:         jekyll-tale
