# Site settings
title: "Wahyu Kristianto"
description: "Creator, Author, Husband, Dad • Making ♥ with thinking & typing •"
baseurl: ""
url: "https://wahyukristianto.com"

# Google Analytics
google_analytics: UA-156793259-1

# Author
author:
  name: "Wahyu Kristianto"
  url: https://wahyukristianto.com
  email: w.kristories@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

repository: Kristories/kristories.github.io

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-github-metadata

# Permalinks
permalink:      /blog/post/:title
paginate:       5
paginate_path: /blog/page/:num/

exclude: [ BU ]