# Site settings
title:          "Wahyu Kristianto"
description:    "Creator, Author, Husband, Dad • Making ♥ with thinking & typing •"
baseurl:        ""
url:            "https://wahyukristianto.com"

# Google Analytics
google_analytics: UA-156793259-1

# Author
author:  "Wahyu Kristianto"
email:        w.kristories@gmail.com

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

# Permalinks
permalink:      /blog/post/:title
paginate:       5
paginate_path: /blog/page/:num/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
